### GET all Movies
GET http://localhost:3000/movies

### GET a Movie by ID
GET http://localhost:3000/movies/e928473a-3331-11ef-8fb0-50e0859c1e71

### POST a new Movie
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Shawshank Redemption PEPITO 2",
    "year": 1994,
    "duration": 142,
    "poster": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
    "rate": 9.3,
    "trailer": "https://www.youtube.com/watch?v=6hB3S9bIaco",
    "status": "Released",
    "budget": 25000000,
    "revenue": 28341469,
    "actors": ["Billy Zane"],
    "directors": ["Peter Jackson","Leandro Rey"],
    "genres": ["Drama"],
    "overview": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical"
}

### POST a new Movie 2
POST http://localhost:3000/movies
Content-Type: application/json

{
    "actors": ["Ex fugiat qui irure"],
    "budget": 80,
    "directors": ["Non culpa et ipsum"],
    "duration": 65,
    "genres": ["Autem facere volupta"],
    "overview": "Quis anim consequat",
    "poster": "https://www.corylafeqaqywex.in",
    "rate": 2,
    "revenue": 1,
    "status": "Planned",
    "title": "Consequatur tempor",
    "trailer": "https://www.taqomokumyne.info",
    "year": 1983
}

### POST a new Movie without required fields to get a validation error
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Matrix",
    "genre": "action",
    "year": 1999
}

### DELETE /movies by ID
DELETE http://localhost:3000/movies/dc473422-79c3-46d3-af5e-25ce0de4b2d1

### PATCH /movies by ID
PATCH http://localhost:3000/movies/4d2085a1-3ca9-43ee-b6b9-77021623d461
Content-Type: application/json

{
    "title": "LA PELICULA PEPITO MODIFICADA",
    "year": 1994,
    "duration": 142,
    "poster": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
    "rate": 9.3,
    "trailer": "https://www.youtube.com/watch?v=6hB3S9bIaco",
    "status": "Released",
    "budget": 333,
    "revenue": 333,
    "actors": ["YO MISMO"],
    "directors": ["Peter Jackson","Leandro Rey"],
    "genres": ["Action,Fantasy,Drama"],
    "overview": "orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

### PATCH /movies by ID
PATCH http://localhost:3000/movies/dd59defa-d5ab-4051-8463-9469f4652122
Content-Type: application/json

{
    "genres": ["Action,Fantasy,Drama"]
}

### POST Create a new User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Pepito",
    "lastname": "Perez",
    "email": "pepito@pepe.com",
    "password": "123456",
    "birthdate": "1990-01-01",
    "country": "Argentina"
}

### POST Login an User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "pepito@pepe.com",
    "password": "123456"
}

### GET if an user is logged in
GET http://localhost:3000/auth

### POST Logout an User
POST http://localhost:3000/auth/logout
Content-Type: application/json
