### GET all Movies
GET http://localhost:3000/movies

### GET a Movie by ID
GET http://localhost:3000/movies/e928473a-3331-11ef-8fb0-50e0859c1e71

### POST a new Movie
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Shawshank Redemption PEPITO",
    "year": 1994,
    "duration": 142,
    "poster": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
    "rate": 9.3,
    "trailer": "https://www.youtube.com/watch?v=6hB3S9bIaco",
    "status": "Released",
    "budget": 25000000,
    "revenue": 28341469,
    "actors": ["Billy Zane"],
    "directors": ["Peter Jackson","Leandro Rey"],
    "genres": ["Drama"]
}

### POST a new Movie without required fields to get a validation error
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Matrix",
    "genre": "action",
    "year": 1999
}

### DELETE /movies by ID
DELETE http://localhost:3000/movies/dd8eabd6-e4f7-4287-8c53-c32344c11ec2

### PATCH /movies by ID
PATCH http://localhost:3000/movies/dd59defa-d5ab-4051-8463-9469f4652122
Content-Type: application/json

{
    "title": "LA PELICULA PEPITO MODIFICADA",
    "year": 1994,
    "duration": 142,
    "poster": "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
    "rate": 9.3,
    "trailer": "https://www.youtube.com/watch?v=6hB3S9bIaco",
    "status": "Released",
    "budget": 333,
    "revenue": 333,
    "actors": ["YO MISMO"],
    "directors": ["Peter Jackson","Leandro Rey"],
    "genres": ["Drama"]
}

### POST Create a new User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Pepito",
    "lastname": "Perez",
    "email": "pepito@pepe.com",
    "password": "123456",
    "birthdate": "1990-01-01",
    "country": "Argentina"
}

### POST Login an User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "pepito@pepe.com",
    "password": "123456"
}
